// select

$(document).ready(function() {
		$("select").searchable({
			maxListSize: 50,						// if list size are less than maxListSize, show them all
			maxMultiMatch: 50,						// how many matching entries should be displayed
			exactMatch: false,						// Exact matching on search
			wildcards: true,						// Support for wildcard characters (*, ?)
			ignoreCase: true,						// Ignore case sensitivity
			latency: 200,							// how many millis to wait until starting search
			warnMultiMatch: 'top {0} matches ...',	// string to append to a list of entries cut short by maxMultiMatch 
			warnNoMatch: 'no matches ...',			// string to show in the list when no entries match
			zIndex: 'auto'							// zIndex for elements generated by this plugin
	   	});
	});




// checkbox

jQuery(document).ready(function() {
	jQuery(".niceCheck").each(function() {
		changeCheckStart(jQuery(this));
    });
});

function changeCheck(el) {

	var el = el,
		input = el.find("input").eq(0);
		  
	if(el.attr("class").indexOf("niceCheckDisabled")==-1)
	{	
   		if(!input.attr("checked")) {
			el.addClass("niceChecked");
			input.attr("checked", true);
		} else {
			el.removeClass("niceChecked");
			input.attr("checked", false).focus();
		}
	}
	
    return true;
}

function changeVisualCheck(input) {

var wrapInput = input.parent();
	if(!input.attr("checked")) {
		wrapInput.removeClass("niceChecked");
	} else {
		wrapInput.addClass("niceChecked");
	}
}

function changeCheckStart(el) {
	try {

	var el = el,
		checkName = el.attr("name"),
		checkId = el.attr("id"),
		checkChecked = el.attr("checked"),
		checkDisabled = el.attr("disabled"),
		checkTab = el.attr("tabindex"),
	    checkValue = el.attr("value");

		if(checkChecked){
			el.after("<span class='niceCheck niceChecked'>"+
				"<input type='checkbox'"+
				"name='"+checkName+"'"+
				"id='"+checkId+"'"+
				"checked='"+checkChecked+"'"+
	            "value='"+checkValue+"'"+
				"tabindex='"+checkTab+"' /></span>");
		} else {
			el.after("<span class='niceCheck'>"+
				"<input type='checkbox'"+
				"name='"+checkName+"'"+
				"id='"+checkId+"'"+
	             "value='"+checkValue+"'"+
				"tabindex='"+checkTab+"' /></span>");
		}
		
		if(checkDisabled) {
			el.next().addClass("niceCheckDisabled");
			el.next().find("input").eq(0).attr("disabled","disabled");
		}
		
		el.next().bind("mousedown", function(e) { changeCheck(jQuery(this)) });
		el.next().find("input").eq(0).bind("change", function(e) { changeVisualCheck(jQuery(this)) });
		
		if(jQuery.browser.msie) {
			el.next().find("input").eq(0).bind("click", function(e) { changeVisualCheck(jQuery(this)) });	
		}

		el.remove();
	}

catch(e)
{
	// если ошибка, ничего не делаем
}

    return true;
}

// Menu


$(document).ready(function(){
  $('a').on('click', function(e){
    e.preventDefault();
  });
    
  $('.menu li').hover(function () {
     clearTimeout($.data(this,'timer'));
     $('ul',this).stop(true,true).slideDown(500);
  }, function () {
    $.data(this,'timer', setTimeout($.proxy(function() {
      $('ul',this).stop(true,true).slideUp(500);
    }, this), 100));
  });

});